from __future__ import annotations

"""External-data evaluation of the pavement performance component on NCAT data.

This script deliberately does not calibrate transfer-function coefficients on the
seven evaluation sections.  It runs the as-built structures, compares predicted
and measured terminal rutting, and reports small-sample uncertainty.  It does not
claim field validation of designs generated by iLLM-PD.
"""

import argparse
import copy
import csv
import json
import math
import sys
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List

import numpy as np


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="NCAT as-built external-data evaluation")
    p.add_argument("--project-root", type=Path, default=Path(__file__).resolve().parents[1])
    p.add_argument("--cases", type=Path,
                   default=Path("experiments/ncat_data/ncat_cases.json"))
    p.add_argument("--mastercurves", type=Path,
                   default=Path("experiments/ncat_data/Dynamic Modulus_Mastercurves.xlsx"))
    p.add_argument("--sections", default="all")
    p.add_argument("--temperature-C", type=float, default=22.8)
    p.add_argument("--frequency-Hz", type=float, default=10.0)
    p.add_argument("--beta-r1", type=float, default=1.0)
    p.add_argument("--beta-s1-gran", type=float, default=1.0)
    p.add_argument("--beta-s1-subg", type=float, default=1.0)
    p.add_argument("--bootstrap", type=int, default=10000)
    p.add_argument("--bootstrap-seed", type=int, default=20260713)
    p.add_argument("--sensitivity", action="store_true",
                   help="also run the prespecified temperature/foundation grid")
    p.add_argument("--sensitivity-temperatures-C", default="17.6,22.8,30.0")
    p.add_argument("--sensitivity-foundation-factors", default="0.75,1.0,1.25")
    p.add_argument("--out-dir", type=Path,
                   default=Path("experiments/ncat_external_validation"))
    p.add_argument("--dry-run", action="store_true")
    return p.parse_args()


def resolve(root: Path, path: Path) -> Path:
    return path if path.is_absolute() else root / path


def floats(raw: str) -> List[float]:
    return [float(x.strip()) for x in raw.split(",") if x.strip()]


def selected(cases: Iterable[Dict[str, Any]], raw: str) -> List[Dict[str, Any]]:
    if raw.strip().lower() == "all":
        return list(cases)
    wanted = {x.strip().upper().replace("NCAT_CG_", "")
              for x in raw.split(",") if x.strip()}
    return [c for c in cases
            if c["section_id"].upper().replace("NCAT_CG_", "") in wanted]


def validate_case(case: Dict[str, Any]) -> None:
    sid = case.get("section_id", "unknown")
    ec = case.get("envconfig", {})
    for key in ("init_thickness_m", "init_modulus_MPa", "init_poisson"):
        if len(ec.get(key, [])) != 5:
            raise ValueError(f"{sid}: {key} must contain five values")
    final = case.get("meta", {}).get("measured_final", {})
    for key in ("rut_mm", "ESAL_at_final"):
        value = final.get(key)
        if value is None or not math.isfinite(float(value)) or float(value) <= 0:
            raise ValueError(f"{sid}: invalid measured_final.{key}")


def ranks(x: np.ndarray) -> np.ndarray:
    order = np.argsort(x, kind="mergesort")
    out = np.empty(len(x), dtype=float)
    i = 0
    while i < len(x):
        j = i + 1
        while j < len(x) and x[order[j]] == x[order[i]]:
            j += 1
        out[order[i:j]] = (i + j - 1) / 2.0 + 1.0
        i = j
    return out


def correlation(x: np.ndarray, y: np.ndarray) -> float:
    if len(x) < 2 or np.std(x) == 0 or np.std(y) == 0:
        return math.nan
    return float(np.corrcoef(x, y)[0, 1])


def core_metrics(measured: np.ndarray, predicted: np.ndarray) -> Dict[str, float]:
    err = predicted - measured
    ss_tot = float(np.sum((measured - np.mean(measured)) ** 2))
    return {
        "n": int(len(measured)),
        "mae_mm": float(np.mean(np.abs(err))),
        "rmse_mm": float(np.sqrt(np.mean(err ** 2))),
        "mean_bias_mm": float(np.mean(err)),
        "mape_pct": float(np.mean(np.abs(err) / measured) * 100.0),
        "r2": float(1.0 - np.sum(err ** 2) / ss_tot) if ss_tot > 0 else math.nan,
        "pearson_r": correlation(measured, predicted),
        "spearman_rho": correlation(ranks(measured), ranks(predicted)),
    }


def bootstrap_intervals(measured: np.ndarray, predicted: np.ndarray,
                        n_boot: int, seed: int) -> Dict[str, List[float]]:
    if n_boot <= 0:
        return {}
    rng = np.random.default_rng(seed)
    vals = {"mae_mm": [], "rmse_mm": [], "mean_bias_mm": []}
    n = len(measured)
    for _ in range(n_boot):
        idx = rng.integers(0, n, size=n)
        m = core_metrics(measured[idx], predicted[idx])
        for key in vals:
            vals[key].append(m[key])
    return {f"{key}_95pct_ci": [float(x) for x in np.percentile(value, [2.5, 97.5])]
            for key, value in vals.items()}


def foundation_scaled(case: Dict[str, Any], factor: float) -> Dict[str, Any]:
    clone = copy.deepcopy(case)
    ec = clone["envconfig"]
    # Layer 4 and the subgrade half-space are the uncertain foundation inputs.
    ec["init_modulus_MPa"][3] *= factor
    ec["init_modulus_MPa"][4] *= factor
    ec["E_subgrade"] *= factor
    return clone


def run_one(case: Dict[str, Any], args: argparse.Namespace, xlsx: Path,
            run_fea, rut_fn, temperature_c: float,
            foundation_factor: float) -> Dict[str, Any]:
    import ncat_mepdg_rutting as legacy

    legacy.FREQ_HZ = float(args.frequency_Hz)
    c = foundation_scaled(case, foundation_factor)
    row = legacy.evaluate_section(
        c, str(xlsx), run_fea, rut_fn,
        beta_r1=args.beta_r1,
        beta_s1_gran=args.beta_s1_gran,
        beta_s1_subg=args.beta_s1_subg,
        T_pavement_F=temperature_c * 9.0 / 5.0 + 32.0,
        T_ref_C=temperature_c,
    )
    row.pop("traj", None)
    row["temperature_C"] = float(temperature_c)
    row["foundation_modulus_factor"] = float(foundation_factor)
    row["abs_error_mm"] = abs(float(row["err_mm"]))
    row["ape_pct"] = row["abs_error_mm"] / float(row["meas_rut_mm"]) * 100.0
    return row


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    if not rows:
        return
    keys = list(rows[0])
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    args = parse_args()
    root = args.project_root.resolve()
    sys.path.insert(0, str(root))
    sys.path.insert(0, str(root / "scripts"))
    cases_path = resolve(root, args.cases)
    xlsx = resolve(root, args.mastercurves)
    out_dir = resolve(root, args.out_dir)
    payload = json.loads(cases_path.read_text(encoding="utf-8"))
    cases = selected(payload["cases"], args.sections)
    if not cases:
        raise SystemExit("no NCAT sections selected")
    for case in cases:
        validate_case(case)

    plan = {
        "sections": [c["section_id"] for c in cases],
        "primary_temperature_C": args.temperature_C,
        "frequency_Hz": args.frequency_Hz,
        "calibration": "none; national coefficients fixed before evaluation",
        "bootstrap_replicates": args.bootstrap,
        "sensitivity": bool(args.sensitivity),
        "claim_boundary": (
            "external-data evaluation of the mechanistic performance component; "
            "not field validation of generated designs"
        ),
        "sample_limit": (
            "seven sections share one nominal structural configuration; section-level "
            "variation is principally mixture modulus and observed performance"
        ),
    }
    print(json.dumps(plan, indent=2))
    if args.dry_run:
        return

    import ncat_mepdg_rutting as legacy
    run_fea, rut_fn = legacy.load_fns()
    primary = [run_one(c, args, xlsx, run_fea, rut_fn,
                       args.temperature_C, 1.0) for c in cases]
    measured = np.asarray([r["meas_rut_mm"] for r in primary], dtype=float)
    predicted = np.asarray([r["pred_total_mm"] for r in primary], dtype=float)
    metrics = core_metrics(measured, predicted)
    metrics.update(bootstrap_intervals(measured, predicted,
                                       args.bootstrap, args.bootstrap_seed))

    sensitivity_rows: List[Dict[str, Any]] = []
    if args.sensitivity:
        for temperature in floats(args.sensitivity_temperatures_C):
            for factor in floats(args.sensitivity_foundation_factors):
                for case in cases:
                    sensitivity_rows.append(
                        run_one(case, args, xlsx, run_fea, rut_fn, temperature, factor)
                    )

    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%d_%H%M%S")
    primary_path = out_dir / f"ncat_primary_{stamp}.csv"
    summary_path = out_dir / f"ncat_summary_{stamp}.json"
    write_csv(primary_path, primary)
    sensitivity_path = None
    if sensitivity_rows:
        sensitivity_path = out_dir / f"ncat_sensitivity_{stamp}.csv"
        write_csv(sensitivity_path, sensitivity_rows)
    summary = {
        "analysis_plan": plan,
        "metrics": metrics,
        "files": {
            "primary": str(primary_path),
            "sensitivity": str(sensitivity_path) if sensitivity_path else None,
        },
    }
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps({"summary": str(summary_path), **summary["files"]}, indent=2))


if __name__ == "__main__":
    main()
